### ISSUE TITLE
basic ui features

### ISSUE THREAD

**Issue by JohnnyTheTank** [bmartel/chakra-multiselect#16]
I'm utilizing this component within a live operational setting. I'm curious about the methods to implement fundamental user interface functionalities, including:

- Modifying the background color of the element when one or more elements are selected.
- Incorporating an icon on either the left or right side of the element.
- Customizing the "delete all" icon.
- Altering the malfunctioning drop-down design specifically when `size="sm"`.

<img width="419" alt="image" src="https://github.com/bmartel/chakra-multiselect/assets/6803264/88d73238-ed05-4f33-b133-6f793e930a1e">

Thank you for your help

**Comment by bmartel** [comment]
Hey @JohnnyTheTank 👋 . 

So with regards to
> Modifying the background color of the element when one or more elements are selected

 can you clarify what you mean here? Which element is  having the background changed, and which are the the ones selected?

> Incorporating an icon on either the left or right side of the element.

This doesn't exist but could very easily be added, PR's are always welcome otherwise I can dig into it when I have time.

> Customizing the "delete all" icon.

https://bmartel.github.io/chakra-multiselect/docs/interfaces/MultiSelectProps.html#actionGroupProps

You can specify `actionGroupProps` which has provisions for both the toggle button, and clear button. Through these you can specify any props you wish, and one of these is the `icon` prop which takes a Component.

```tsx
<MultiSelect
    actionGroupProps={{
        clearButtonProps: {
            icon: () => <i>MyIconHere</i>
        }
    }}
/>
```

> Altering the malfunctioning drop-down design specifically when size="sm"

I recently published a fix for all the sizings so sm, md (default), and lg contain the corrected styles. This was a regression from the introduction of the virtualized lists, I apologize 🙏 .

**Comment by JohnnyTheTank** [comment]
Thank you. I think all question got answered. Good job, I love your work!
