### ISSUE TITLE
MultiSelect onChange and value type error

### ISSUE THREAD

**Issue by Nyoubi** [bmartel/chakra-multiselect#33]
Hi bmartel,

I'm having a huge issue with your component and typescript. Using the useMultiSelect hook, it tells me value is of type string[] | string | undefined. But when I log it after calling onChange it contain an Option. I tried it with a StatefulMultiSelect like in your exemple but I have the same issue.

Is it an expected behaviour ? And if yes can you change useMultiSelect hook with correct type for value and onChange ?

Thank you for your help.

**Comment by jamesgasek** [comment]
Having this issue as well.
<img width="200" alt="image" src="https://github.com/bmartel/chakra-multiselect/assets/10537347/b539bfa3-c5dd-4881-bab7-be061da2ce41">
Type '(selectedOptions: Option[]) => void' is not assignable to type 'SelectOnChange'.

**Comment by bmartel** [comment]
Hey there 👋. The type has been fixed in the latest published version, it is indeed supposed to be an Option|Option[] as the value. I've both corrected the error that was initially observed, and consolidated the types across every usage so it should be consistent, and will be a https://bmartel.github.io/chakra-multiselect/docs/types/SelectOnChange.html type.

For the error of `Type '(selectedOptions: Option[]) => void' is not assignable to type 'SelectOnChange'.` ensure you are using the SelectOnChange type to type your function, the selectedOptions type can be further narrowed within your function, but to ensure its compatible without error allow the types to come from SelectOnChange.

https://bmartel.github.io/chakra-multiselect/docs/interfaces/MultiSelectProps.html#onChange
